# Generated by Django 3.0 on 2020-11-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201106_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='terra',
            name='area',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='terra',
            name='loteamento',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='terra',
            name='numero',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='terra',
            name='valor',
            field=models.FloatField(null=True),
        ),
    ]
