# Generated by Django 3.0 on 2020-11-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201106_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='interessado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, null=True)),
                ('cpf', models.CharField(default='Somente numeros', max_length=14, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
