# Generated by Django 3.0 on 2020-11-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_interessado'),
    ]

    operations = [
        migrations.CreateModel(
            name='processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroProcesso', models.CharField(max_length=200, null=True)),
                ('dataProcesso', models.DateField(null=True)),
                ('numFolhas', models.FloatField(null=True)),
                ('numeroTitulo', models.CharField(max_length=200)),
                ('dataTitulo', models.DateField(null=True)),
                ('folha', models.FloatField(null=True)),
                ('livro', models.FloatField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='interessado',
            name='nome',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
