# Generated by Django 3.0 on 2020-11-10 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201106_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='interessado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Interessado'),
        ),
    ]
