# Generated by Django 3.0 on 2020-11-10 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201110_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='observação',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='status',
            field=models.CharField(choices=[('Finalizado', 'Finalizado'), ('Pendente', 'Pendente'), ('Cancelado', 'Cancelado')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='interessado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Interessado'),
        ),
    ]
