# Generated by Django 3.0 on 2020-11-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20201111_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='interessado',
            name='telefone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='interessado',
            field=models.ManyToManyField(to='accounts.Interessado'),
        ),
    ]
