# Generated by Django 3.0 on 2020-11-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20201116_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='interessado',
            field=models.ManyToManyField(to='accounts.Interessado'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='pdf',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
