# Generated by Django 3.0 on 2021-09-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210902_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='interessado',
            field=models.ManyToManyField(to='accounts.Interessado'),
        ),
    ]
