# Generated by Django 3.0 on 2021-09-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20210903_1820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.AlterField(
            model_name='processo',
            name='interessado',
            field=models.ManyToManyField(to='accounts.Interessado'),
        ),
    ]
