# Generated by Django 3.0 on 2021-09-08 22:04

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20210908_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='scpt',
            field=multiselectfield.db.fields.MultiSelectField(choices=[['F', 'Fácil'], ['M', 'Moderado'], ['D', 'Difícil']], max_length=5),
        ),
        migrations.AlterField(
            model_name='processo',
            name='interessado',
            field=models.ManyToManyField(to='accounts.Interessado'),
        ),
    ]
