# Generated by Django 3.0 on 2021-09-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20210910_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='descricao',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='interessado',
            field=models.ManyToManyField(to='accounts.Interessado'),
        ),
    ]
